name: Build Portable Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Windows Executable
        run: flutter build windows --release

      - name: Copy C++ Runtime DLLs (Prevent Missing DLL Errors)
        shell: pwsh
        run: |
          Copy-Item "C:\Windows\System32\vcruntime140.dll" -Destination "build\windows\x64\runner\Release\" -ErrorAction SilentlyContinue
          Copy-Item "C:\Windows\System32\vcruntime140_1.dll" -Destination "build\windows\x64\runner\Release\" -ErrorAction SilentlyContinue
          Copy-Item "C:\Windows\System32\msvcp140.dll" -Destination "build\windows\x64\runner\Release\" -ErrorAction SilentlyContinue

      - name: Package Release inside a Folder (Prevent Extractor Errors)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path build\LOQU_App_Windows
          Copy-Item -Path build\windows\x64\runner\Release\* -Destination build\LOQU_App_Windows -Recurse
          Compress-Archive -Path build\LOQU_App_Windows -DestinationPath LOQU_Windows_Portable.zip

      - name: Upload Output Zip
        uses: actions/upload-artifact@v4
        with:
          name: LOQU-App-Crack-Style
          path: LOQU_Windows_Portable.zip
